import { Inter } from 'next/font/google'
import './globals.css'
import TransitionProvider from '@/components/TransitionProvider/TransitionProvider.jsx'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portafolio Juan Espino',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav></nav>
        <TransitionProvider>{children}</TransitionProvider>
      </body>
    </html>
  )
}
